name: Build LaTeX document
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile thesis
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tesi.tex
      - name: Compile slides
        uses: xu-cheng/latex-action@v2
        with:
          root_file: presentazione.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tesi.pdf
            presentazione.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
